### PR TITLE
Create Pop!_OS Style

### PR DESCRIPTION
**Pull request by ad1tyawagh**
I have changed the following files:

- `color` :       Set Pop!_OS colors
- `rofi.rasi` :   Set Pop!_OS colors
- `theme` :     Set border width to 3px.
- `typeface` :  Set fonts recommended by  **pop-os/gtk-theme** repo

**Added a wallpaper**: kate-hazen-unleash-your-robot-blue.png

### CODE REVIEW

**Comment by kgilmer** [comment]
Great!  Any chance you can provide a screenshot?

**Comment by ad1tyawagh** [comment]
pop-os-regolith
Screenshot from 2020-08-11 12-39-22
Screenshot from 2020-08-11 12-42-55
Screenshot from 2020-08-11 12-44-36
Screenshot from 2020-08-11 12-44-46

**Comment by ad1tyawagh** [comment]
Updated the wallpaper to match the screenshots.

**Comment by kgilmer** [comment]
what gtk theme are we using?

**Comment by kgilmer** [comment]
The screenshots look great by the way, thank you for posting them!

**Comment by ad1tyawagh** [comment]
> what gtk theme are we using?

Since I am running Pop!_OS, I have the pop-gtk theme installed. That is the one I have used.
Have a look at it [here.](https://github.com/pop-os/gtk-theme)
> The screenshots look great by the way, thank you for posting them!

You're welcome!

**Comment by ad1tyawagh** [comment]
Also, I have based my style on the **nord**style.

Should I use base it upon **lascaille** instead?

**Comment by ad1tyawagh** [comment]
Let's merge it!

**Comment by kgilmer** [comment]
Merged, thanks again @ad1tyawagh .  The packages should be available for testing in `unstable` by tomorrow.  A few questions:

1. I noticed you set the icon theme to pop as well, do we need to install a package to get those icons?
2. Is the background image you've added installed by default in pop_os under /usr/share/backgrounds/kate-hazen-unleash-your-robot-blue.png ?

**Comment by ad1tyawagh** [comment]
> I noticed you set the icon theme to pop as well, do we need to install a package to get those icons?

Yes, we need to install a package for it. You will find it in the [system76 PPA](https://launchpad.net/~system76/+archive/ubuntu/pop). Include a package called `pop-icon-theme`. Otherwise a metapackage `pop-theme` should install everything, namely:
- Pop GTK theme (`pop-gtk-theme`)
- Pop icon theme (`pop-icon-theme`)
- Pop sound theme (`pop-sound-theme`)

There is a package - `pop-fonts` which will install all the pop fonts.

> Is the background image you've added installed by default in pop_os under /usr/share/backgrounds/kate-hazen-unleash-your-robot-blue.png ?

I have assumed that you have a script that will copy the files in the correct place, hence the path in the XML file is `/usr/share/backgrounds/kate-hazen-unleash-your-robot-blue.png`. The path in Pop!_OS is : `/usr/share/backgrounds/pop/kate-hazen-unleash-your-robot-blue.png`. The package `pop-wallpapers` installs all the pop wallpapers in the `/usr/share/backgrounds/pop` folder.

Refer to the image below.

pop-background

**Comment by kgilmer** [comment]
Is this the font you want to go with for Rofi?

image

**Comment by ad1tyawagh** [comment]
Yes, that's the default sans font of Pop!_OS.

**Comment by kgilmer** [comment]
:+1:

**Pull request merged**
