### PR TITLE
date format now follows locale

### PR DESCRIPTION
**Pull request by ploum**
note that I haven't tested it. 
Also, this means that years and seconds are now displayed.

### CODE REVIEW

**Comment by kgilmer** [comment]
Hmm, not excited about having the seconds on the bar.  It seems that `date` does not provide a locale specific way of getting the time without the seconds.  How about getting the date in locale format and defaulting the clock to 24 hour format or 12 hour format based on the value of `gsettings set org.gnome.desktop.interface clock-format`?  Do you see problems with this approach?

**Comment by ploum** [comment]
I understand. Is there a way to display the output of a random command ? I could try to make a little command that output what we want.

**Comment by kgilmer** [comment]
Yes.  well i3blocks just launches scripts to collect data for each 'blocklet'.  The existing shell script that generates the time is here: https://github.com/regolith-linux/regolith-i3xrocks-config/blob/master/scripts/time

You can just execute the script and the output is what's fed back into i3bar.

**Comment by kgilmer** [comment]
This change is addressed in the time2 script in regolith-i3xrocks-config.  Closing.

**Pull request closed without merging**
