### PR TITLE
Add midnight theme

### PR DESCRIPTION
**Pull request by naib864**
Here is my pull request for the midnight-based theme. Put the files for fonts, icons and gtk theme in a subdirectory for now.

### CODE REVIEW

**Comment by moritzheiber** [comment]
Thank you for your work. I'm not entirely sure whether we want to ship an entire GTK theme as an included dependency though :thinking: 

@kgilmer @cheginit Opinions?

**Comment by naib864** [comment]
Yeah, I wasn't sure about that either. Will look if I can maybe find a similar theme in the apt sources meanwhile.

**Comment by naib864** [comment]
Is it possible to modify a gtk theme during the installation after it has been installed as dependency?
Main problem I had with other themes were the colors. If the look could use the `arc-theme` and just change the colors within the theme files, that would work for the look as well.
Or create a new gtk theme by copying the arc theme and editing this copy during installation process.

**Comment by moritzheiber** [comment]
I think the most feasible way would be to create the theme as a separately packaged dependency (including the color changes; no changing package content after the fact, that's a no-no) and then have this style depend on the GTK theme.

**Comment by naib864** [comment]
Okay. I'm pretty new to packaging stuff (and contributing to open source alltogether), so don't really know how to do that yet. Trying to learn new things :)

**Comment by cheginit** [comment]
I agree with @moritzheiber, I think any new Regolith theme should follow the same packaging strategy as the other themes.

**Comment by kgilmer** [comment]
Yeah I discussed w/ @naib864 on slack before he submitted the PR regarding the gtk theme and icon dependencies.  We'll need to package those up as well.  I've had a relatively hard time w/ gtk themese in the past due to symlinks not being packagable but required by these themes.  Also they generally have very sloppy "build" scripts.  Last year I spent some time trying to adapt https://github.com/pop-os/gtk-theme as a general purpose template for gtk themes but ran into some weird build issues.  I think the issue has since been addressed so I'll take another pass.  If anyone else is aware of a clean, meson-based gtk theme that builds w/ debian packaging please LMK.

**Comment by naib864** [comment]
Can I somehow help with that? I don't wanna put too much work on your backs just for something rather unimportant like a theme.

**Comment by kgilmer** [comment]
It's not a problem.  I typically package a few new themes w/ each release, otherwise things start to look stale.  However, you're more than welcome to dig into reading about debian packaging, but I think it could be awhile before you had enough knowledge to successfully package a gtk theme.  

As a first try, maybe something like:

```bash
$ git clone https://github.com/pop-os/gtk-theme.git
$ cd gtk-theme
$ debuild
```

You may get all the way to a key error which means you were able to build the package but could not sign it as you don't have the key for the pop-os cert.  That is resolved by prepending to the `debian/changelog` file.  If you end up giving it a try but get stuck let us know and we'll do our best to help you out.  :smile:

**Comment by naib864** [comment]
Alright, will give it a try :)

**Comment by kgilmer** [comment]
May be of interest: https://github.com/regolith-linux/regolith-system/wiki/Rewrite-of-regolith-styles

**Comment by kgilmer** [comment]
hi @naib864 , I'm pretty sure you packaged a gtk theme.  I've searched my mail but cannot find our discussion.  Where is your work again?

**Comment by naib864** [comment]
@kgilmer we talked about it in slack :D

**Comment by kgilmer** [comment]
Hi @naib864 , I've begun the work to integrate your new look into Regolith.  Since we have the gtk and icon themes as seperate repos now can you remove those from this PR?

**Comment by naib864** [comment]
Done @kgilmer. What about the font?

**Comment by kgilmer** [comment]
Yes if the font is custom we'll need either an existing package in Ubuntu repos (ideal) or package it ourselves.  I didn't see a repo in your github for this.  Have you looked into it?

**Comment by naib864** [comment]
Yeah, I just looked. There doesn't seem to exist any packages for this font or even the nerd fonts in general. Will look if I can use another font that fits or will create a new repo for it.

**Comment by kgilmer** [comment]
Sounds good, will hold on further integration of new look.  BTW the gtk and icon theme packages are available for testing in the `unstable` PPA.

**Comment by naib864** [comment]
I made a new [repository](https://github.com/naib864/regolith-nerd-font-iosevka) for the font package.

**Comment by kgilmer** [comment]
Great, forked to [here](https://github.com/regolith-linux/nerd-font-iosevka) (I prefer to keep the repo and package names the same if I can, less unnecessary variance)

Building now in `experiemental`: https://launchpad.net/~regolith-linux/+archive/ubuntu/experimental/+packages?field.name_filter=sevka&field.status_filter=published&field.series_filter=

Will build this in `unstable` if goes well and then I think we can wrap it all up!

**Comment by kgilmer** [comment]
The control file needs to be updated to add the new dependencies but i can do that post merge, it's a quick fix.

**Comment by naib864** [comment]
Oh yeah, forgot that

**Comment by kgilmer** [comment]
No worries @naib864 .  This is now building into the `unstable` PPA as `regolith-styles` `1.8.0-1` and should be available for all active Ubuntu releases (18.04, 20.04, 20.10) by EOD.  I will do some testing but would be great if you could as well to ensure everything looks as you would expect.

**Comment by naib864** [comment]
Alright, will test it now on some of my machines :)

**Comment by kgilmer** [comment]
I made a few more edits...I think it's mostly good except for the bar glyphs.  I was unsure if you were looking to use the material design webfont or the icons built into the nerd font.  But I assume the latter.  I removed the materialdesign icons from the `typeface` file.  Looks like the icons are off though.  May need to update the values for each icon in the `typeface` file or LMK if there is something wrong with how I specify the fonts, also in that file.

image

**Comment by naib864** [comment]
Okay, that's weird. I'll look into it.

**Comment by naib864** [comment]
@kgilmer For me everything looks normal. Fresh install of the regolith with installation of `regolith-look-midnight` afterwards.

**Comment by kgilmer** [comment]
great!  Do you have a wallpaper in mind?  that file can go into the `regolith-look-midnight` package.

**Comment by kgilmer** [comment]
what version of Ubuntu are you testing on @naib864 ?

**Comment by naib864** [comment]
I used the latest regolith iso.

**Comment by cheginit** [comment]
Great work on the theme. I just gave it a try and it looks good.

One suggestion though, the red color that appears when there's a notification on an unfocused workspace can be changed in my opinion:
image

It doesn't worked well with the white font and blue icon. The opposite color to blue on the color wheel is yellow, so an orange-ish color might look better.

**Comment by cheginit** [comment]
I just noticed that each workspace icon has a different color. So I guess it doesn't make a difference what color you set, it's not gonna look good in all of them.

**Pull request merged**
